version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
    commit-message:
      prefix: "build(deps)"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
    commit-message:
      prefix: "build(deps)"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"

    groups:
      internal-configs:
        patterns:
          - "@krudi/*"
          - "@gympli/*"
        update-types: ["minor", "patch"]

      build-tools:
        patterns:
          - "typescript"
          - "ts-node"
        update-types:
          - "minor"
          - "patch"

      linting-and-formatting:
        patterns:
          - "eslint"
          - "eslint-plugin-*"
          - "eslint-config-*"
          - "prettier"
        update-types:
          - "minor"
          - "patch"
