version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
    commit-message:
      prefix: "build(deps)"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
    commit-message:
      prefix: "build(deps)"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"

    groups:
      internal-configs:
        patterns:
          - "@krudi/eslint-config"
          - "@krudi/prettier-config"
        update-types:
          - "minor"
          - "patch"

      build-tools:
        patterns:
          - "typescript"
          - "ts-node"
          - "typescript-eslint"
        update-types:
          - "minor"
          - "patch"

      linting-and-formatting:
        patterns:
          - "prettier"
        update-types:
          - "minor"
          - "patch"
