version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
    commit-message:
      prefix: "build(deps)"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
    commit-message:
      prefix: "build(deps)"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"

    groups:
      internal-configs:
        patterns:
          - "@krudi/eslint-config"
          - "@krudi/typescript-config"
          - "@krudi/prettier-config"
        update-types:
          - "minor"
          - "patch"

      build-tools:
        patterns:
          - "typescript"
          - "ts-node"
          - "typescript-eslint"
          - "@typescript-eslint/eslint-plugin"
          - "@typescript-eslint/parser"
          - "turbo"
        update-types:
          - "minor"
          - "patch"

      typings:
        patterns:
          - "@types/node"
        update-types:
          - "minor"
          - "patch"

      linting-and-formatting:
        patterns:
          - "eslint"
          - "eslint-config-prettier"
          - "eslint-config-expo"
          - "eslint-config-flat-gitignore"
          - "eslint-flat-config-utils"
          - "eslint-plugin-prettier"
          - "eslint-plugin-simple-import-sort"
          - "eslint-plugin-turbo"
          - "@eslint/js"
          - "@eslint/eslintrc"
          - "@eslint/compat"
          - "@next/eslint-plugin-next"
          - "prettier"
        update-types:
          - "minor"
          - "patch"

      utilities:
        patterns:
          - "globals"
          - "jiti"
        update-types:
          - "minor"
          - "patch"
