name: Lint

on: [push, pull_request]

concurrency:
    group: lint-${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

permissions:
    contents: read

jobs:
    lint:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                node-version: ['22.18.0']
                lint-commands:
                    - npm run lint:eslint

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Node.js environment
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: npm
                  registry-url: https://registry.npmjs.org

            - name: Install dependencies
              run: npm install

            - name: Build workspace
              run: npm run build

            - name: Run linting command (${{ matrix.lint-commands }})
              run: ${{ matrix.lint-commands }}
