name: Publish prettier-config

on:
  release:
    types: [published]

  workflow_dispatch:

concurrency:
  group: publish-prettier-config-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    if: ${{ github.event_name == 'workflow_dispatch' || startsWith(github.event.release.tag_name, '@krudi/prettier-config@') }}
    permissions:
      contents: read
      id-token: write
    uses: krudi/reusable-actions/.github/workflows/publish-npm.yaml@main
    with:
      workspace: "@krudi/prettier-config"
      node_version_file: .nvmrc
    secrets:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
