name: Publish

on:
    push:
        tags:
            - '@krudi/*@*'

    workflow_dispatch:

concurrency:
    group: publish-${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

permissions:
    contents: write
    id-token: write

jobs:
    publish:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                node-version: ['22.18.0']

        steps:
            - name: Checkout repository
              uses: actions/checkout@v5

            - name: Set up Node.js environment
              uses: actions/setup-node@v6
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: npm
                  registry-url: https://registry.npmjs.org

            - name: Install dependencies
              run: npm install

            - name: Compile and build
              run: npm run build

            - name: Publish tagged package
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
                  NPM_CONFIG_PROVENANCE: 'true'
              run: |
                  PKG_TAG="${GITHUB_REF_NAME}"
                  PKG_NAME="${PKG_TAG%@*}"
                  echo "Publishing $PKG_NAME"
                  npm publish --workspace="$PKG_NAME" --access public --provenance --no-git-checks
